name: image_recognition
description: Image recognition plugin using TensorFlow Lite with full integer quantization for offline mobile inference.
version: 1.0.0
homepage: https://github.com/percepthor/image_recognition

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^9.0.1
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.percepthor.image_recognition
        pluginClass: ImageRecognitionPlugin
      ios:
        pluginClass: ImageRecognitionPlugin

  # Assets will be bundled from the app, not the plugin
  # Apps using this plugin should include:
  # flutter:
  #   assets:
  #     - assets/image_recognition/model_qat_int8.tflite
  #     - assets/image_recognition/labels.txt
  #     - assets/image_recognition/threshold_recommendation.json
  #     - assets/image_recognition/runtime_config.json

ffigen:
  name: ImageRecognitionBindings
  description: FFI bindings for image_recognition native library
  output: 'lib/src/bindings.g.dart'
  headers:
    entry-points:
      - 'native/include/image_recognition.h'
    include-directives:
      - '**image_recognition.h'
  comments:
    style: any
    length: full
  preamble: |
    // AUTO-GENERATED FILE - DO NOT EDIT
    // Generated by ffigen from native/include/image_recognition.h
    //
    // This file contains FFI bindings for the image_recognition native library.
    // Do not modify this file manually.
